spring:
  application:
    name: order-service
  datasource:
    url: ${DATABASE_URL_ORDER_SERVICE}
    username: ${DATABASE_USERNAME_ORDER_SERVICE}
    password: ${DATABASE_PASSWORD_ORDER_SERVICE}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVER_URL}
  instance:
    hostname: ${INSTANCE_HOSTNAME}
    instance-id: ${spring.application.name}:${random.uuid}