version: '3.8'

services:
  config-server:
    build:
      context: ./config-service
      dockerfile: Dockerfile
    container_name: config-server
    ports:
      - "8888:8888"
    env_file:
      - .env
    networks:
      - microservice-network

  discovery-server:
    build:
      context: ./discovery-server
      dockerfile: Dockerfile
    container_name: discovery-server
    ports:
      - "8761:8761"
    env_file:
      - .env
    depends_on:
      config-server:
        condition: service_started
    networks:
      - microservice-network

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      config-server:
        condition: service_started
      discovery-server:
        condition: service_started
    networks:
      - microservice-network

  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    container_name: product-service
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      config-server:
        condition: service_started
      discovery-server:
        condition: service_started
    networks:
      - microservice-network

  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    container_name: order-service
    ports:
      - "8081:8081"
    env_file:
      - .env
    depends_on:
      config-server:
        condition: service_started
      discovery-server:
        condition: service_started
    networks:
      - microservice-network

networks:
  microservice-network:
    driver: bridge